<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://arizasud.uz/</loc>
        <lastmod>2025-03-19</lastmod>
        <changefreq>daily</changefreq>
        <priority>1.0</priority>
    </url>
    <url>
        <loc>https://arizasud.uz/login</loc>
        <lastmod>2025-03-19</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>https://arizasud.uz/appeals</loc>
        <lastmod>2025-03-19</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://arizasud.uz/register</loc>
        <lastmod>2025-03-19</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://arizasud.uz/contact</loc>
        <lastmod>2025-03-19</lastmod>
        <changefreq>yearly</changefreq>
        <priority>0.4</priority>
    </url>
</urlset>
